### ISSUE TITLE
the deployed website isnt working for me😔😔

### ISSUE THREAD

**Issue by quat1024** [TheOriginalAyaka/sekai-stickers#6]
https://st.ayaka.one/ is a blank white page 4 me

if i go on `view source` the 2 urls https://st.ayaka.one/static/js/main.12a1fd73.js and https://st.ayaka.one/static/css/main.5785952b.css appear in the source, but clicking on them takes me to this vercel 404 page:

![Screenshot_20221013-162420](https://user-images.githubusercontent.com/2068021/195704030-c1acb4c5-7b69-49f4-b2db-1c57f443d5c1.png) the link goes here https://vercel.com/docs/concepts/edge-network/frequently-asked-questions#why-do-i-see-a-404-error-when-accessing-my-deployment

the urls like apple touch icon and the favicon are not 404ing though

and actually the website worked last night when i went on it 😩 and it seems to be working for other people on discord too

**Comment by TheOriginalAyaka** [comment]
try clearing the cache, because I'm too smart I deployed a service worker that uses those old URLs xd, skill issue.
this issue happens only to people that used the website before 13/10/2022

**Comment by quat1024** [comment]
it works ‼️ thanks
